module.exports = {
  ProductosRepository: require("./ProductosRepository"),
  OfertasRepository: require("./OfertasRepository"),
  CarritoRepository: require("./CarritoRepository"),
  ClientesRepository: require("./ClientesRepository"),
  CuponesRepository: require("./CuponesRepository"),
  EmpleadosRepository: require("./EmpleadosRepository"),
  FavoritosRepository: require("./FavoritosRepository"),
  CampanasRepository: require("./CampanasRepository"),
  ProductosCampanasRepository: require("./ProductosCampanasRepository"),
  AuthRepository: require("./AuthRepository"),
  MedicosRepository: require("./MedicosRepository"),
  PermisosRepository: require("./PermisosRepository"),
  RecetasRepository: require("./RecetasRepository"),
  VentasOnlineRepository: require("./VentasOnlineRepository"),
  VentasEmpleadosRepository: require("./VentasEmpleadosRepository"),
  MensajesRepository: require("./MensajesRepository"),
  ReportesRepository: require("./ReportesRepository"),
  MercadoPagoRepository: require("./MercadoPagoRepository"),
};
