module.exports = {
  AuthService: require("./AuthService"),
  BirthdayCouponScheduler: require("./BirthdayCouponScheduler"),
  CampanasService: require("./CampanasService"),
  CarritoService: require("./CarritoService"),
  ClientesService: require("./ClientesService"),
  CloudinaryService: require("./CloudinaryService"),
  CuponesService: require("./CuponesService"),
  CuponesCumpleanosService: require("./CuponesCumpleanosService"),
  DashboardService: require("./DashboardService"),
  EmpleadosService: require("./EmpleadosService"),
  FavoritosService: require("./FavoritosService"),
  ImagenesProductosService: require("./ImagenesProductosService"),
  MedicosService: require("./MedicosService"),
  MensajesService: require("./MensajesService"),
  MercadoPagoService: require("./MercadoPagoService"),
  NewsletterService: require("./NewsletterService"),
  PermisosService: require("./PermisosService"),
  ProductosService: require("./ProductosService"),
  RecetasService: require("./RecetasService"),
  ReportesService: require("./ReportesService"),
  TicketService: require("./TicketService"),
  VentasEmpleadosService: require("./VentasEmpleadosService"),
  VentasOnlineService: require("./VentasOnlineService"),
};
