module.exports = {
  AuthService: require("./AuthService"),
  CampanasService: require("./CampanasService"),
  CarritoService: require("./CarritoService"),
  ClientesService: require("./ClientesService"),
  CuponesService: require("./CuponesService"),
  EmpleadosService: require("./EmpleadosService"),
  FavoritosService: require("./FavoritosService"),
  MedicosService: require("./MedicosService"),
  MensajesService: require("./MensajesService"),
  MercadoPagoService: require("./MercadoPagoService"),
  OfertasService: require("./OfertasService"),
  PermisosService: require("./PermisosService"),
  ProductosService: require("./ProductosService"),
  RecetasService: require("./RecetasService"),
  ReportesService: require("./ReportesService"),
  VentasEmpleadosService: require("./VentasEmpleadosService"),
  VentasOnlineService: require("./VentasOnlineService"),
};
