module.exports = {
  AuthController: require("./AuthController"),
  AuditoriaController: require("./AuditoriaController"),
  CampanasController: require("./CampanasController"),
  CarritoController: require("./CarritoController"),
  ClientesController: require("./ClientesController"),
  CloudinaryController: require("./CloudinaryController"),
  CuponesController: require("./CuponesController"),
  DashboardController: require("./DashboardController"),
  EmpleadosController: require("./EmpleadosController"),
  FavoritosController: require("./FavoritosController"),
  ImagenesProductosController: require("./ImagenesProductosController"),
  MedicosController: require("./MedicosController"),
  MensajesController: require("./MensajesController"),
  MercadoPagoController: require("./MercadoPagoController"),
  NewsletterController: require("./NewsletterController"),
  PermisosController: require("./PermisosController"),
  ProductosController: require("./ProductosController"),
  RecetasController: require("./RecetasController"),
  ReportesController: require("./ReportesController"),
  TicketController: require("./TicketController"),
  VentasEmpleadosController: require("./VentasEmpleadosController"),
  VentasOnlineController: require("./VentasOnlineController"),
};
