module.exports = {
  AuthRoutes: require("./AuthRoutes"),
  AuditoriaRoutes: require("./AuditoriaRoutes"),
  CampanasRoutes: require("./CampanasRoutes"),
  CarritoRoutes: require("./CarritoRoutes"),
  ClientesRoutes: require("./ClientesRoutes"),
  CloudinaryRoutes: require("./CloudinaryRoutes"),
  CuponesRoutes: require("./CuponesRoutes"),
  DashboardRoutes: require("./DashboardRoutes"),
  EmpleadosRoutes: require("./EmpleadosRoutes"),
  FavoritosRoutes: require("./FavoritosRoutes"),
  ImagenesProductosRoutes: require("./ImagenesProductosRoutes"),
  MedicosRoutes: require("./MedicosRoutes"),
  MensajesRoutes: require("./MensajesRoutes"),
  MercadoPagoRoutes: require("./MercadoPagoRoutes"),
  NewsletterRoutes: require("./NewsletterRoutes"),
  PermisosRoutes: require("./PermisosRoutes"),
  ProductosRoutes: require("./ProductosRoutes"),
  RecetasRoutes: require("./RecetasRoutes"),
  ReportesRoutes: require("./ReportesRoutes"),
  TicketRoutes: require("./TicketRoutes"),
  VentasEmpleadosRoutes: require("./VentasEmpleadosRoutes"),
  VentasOnlineRoutes: require("./VentasOnlineRoutes"),
};
