module.exports = {
  AuthRoutes: require("./AuthRoutes"),
  AuditoriaRoutes: require("./AuditoriaRoutes"),
  CampanasRoutes: require("./CampanasRoutes"),
  CarritoRoutes: require("./CarritoRoutes"),
  ClientesRoutes: require("./ClientesRoutes"),
  CuponesRoutes: require("./CuponesRoutes"),
  DashboardRoutes: require("./DashboardRoutes"),
  EmpleadosRoutes: require("./EmpleadosRoutes"),
  FavoritosRoutes: require("./FavoritosRoutes"),
  ImagenesProductosRoutes: require("./ImagenesProductosRoutes"),
  MedicosRoutes: require("./MedicosRoutes"),
  MensajesRoutes: require("./MensajesRoutes"),
  MercadoPagoRoutes: require("./MercadoPagoRoutes"),
  // REMOVED: OfertasRoutes: require("./OfertasRoutes"), // DEPRECATED - usar CampanasRoutes
  PermisosRoutes: require("./PermisosRoutes"),
  ProductosRoutes: require("./ProductosRoutes"),
  RecetasRoutes: require("./RecetasRoutes"),
  ReportesRoutes: require("./ReportesRoutes"),
  VentasEmpleadosRoutes: require("./VentasEmpleadosRoutes"),
  VentasOnlineRoutes: require("./VentasOnlineRoutes"),
};
