module.exports = {
  AuthSchemas: require("./AuthSchemas"),
  CampanasSchemas: require("./CampanasSchemas"),
  CarritoSchemas: require("./CarritoSchemas"),
  ClienteSchemas: require("./ClienteSchemas"),
  DashboardSchemas: require("./DashboardSchemas"),
  EmpleadoSchemas: require("./EmpleadoSchemas"),
  FavoritoSchemas: require("./FavoritoSchemas"),
  MedicoSchemas: require("./MedicoSchemas"),
  MensajeSchemas: require("./MensajeSchemas"),
  MercadoPagoSchemas: require("./MercadoPagoSchemas"),
  OfertasSchemas: require("./OfertasSchemas"),
  PermisoSchemas: require("./PermisoSchemas"),
  ProductoSchemas: require("./ProductoSchemas"),
  RecetaSchemas: require("./RecetaSchemas"),
  ReporteSchemas: require("./ReporteSchemas"),
  VentaEmpleadoSchemas: require("./VentaEmpleadoSchemas"),
  VentaOnlineSchemas: require("./VentaOnlineSchemas"),
};
